### ISSUE TITLE
Why is the batch size so small?

### ISSUE THREAD

**Issue by zinccat** [arobey1/mbdg#1]
In code files that create dataloaders, I found that batchsize=1, I wonder is there any particular reason that you set this value so small? Thanks

**Comment by arobey1** [comment]
This is the default batch size for MUNIT (see Appendix B of https://arxiv.org/pdf/1804.04732.pdf).  When training classifiers, the default batch size should be larger.

**Comment by zinccat** [comment]
Thanks!
